// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelReviewApp.Data;

#nullable disable

namespace FirstAspNetCoreWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelReviewApp.Models.Admin", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("AdminLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastActionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AdminLevel = 2,
                            LastActionTime = new DateTime(2023, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Permissions = "All"
                        });
                });

            modelBuilder.Entity("TravelReviewApp.Models.AdminAction", b =>
                {
                    b.Property<int>("ActionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionID"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ActionID");

                    b.HasIndex("AdminID");

                    b.ToTable("AdminActions");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Amenity", b =>
                {
                    b.Property<int>("AmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AmenityID");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            AmenityID = 1,
                            Category = "General",
                            Description = "Free WiFi",
                            Name = "WiFi"
                        },
                        new
                        {
                            AmenityID = 2,
                            Category = "Hotel",
                            Description = "Outdoor swimming pool",
                            Name = "Swimming Pool"
                        },
                        new
                        {
                            AmenityID = 3,
                            Category = "General",
                            Description = "Free parking on premises",
                            Name = "Parking"
                        },
                        new
                        {
                            AmenityID = 4,
                            Category = "Dining",
                            Description = "On-site restaurant",
                            Name = "Restaurant"
                        },
                        new
                        {
                            AmenityID = 5,
                            Category = "Dining",
                            Description = "On-site bar",
                            Name = "Bar"
                        });
                });

            modelBuilder.Entity("TravelReviewApp.Models.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Clicked")
                        .HasColumnType("bit");

                    b.Property<int>("FacilityID")
                        .HasColumnType("int");

                    b.Property<string>("ProviderURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("FacilityID");

                    b.HasIndex("UserID");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Facility", b =>
                {
                    b.Property<int>("FacilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityID"));

                    b.Property<int>("AddedByUserID")
                        .HasColumnType("int");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int?>("LastModifiedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("FacilityID");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("TravelReviewApp.Models.FacilityAmenity", b =>
                {
                    b.Property<int>("FacilityID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AmenityID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("FacilityID", "AmenityID");

                    b.HasIndex("AmenityID");

                    b.ToTable("FacilityAmenities");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacilityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedByUserID")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageID");

                    b.HasIndex("FacilityID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacilityID")
                        .HasColumnType("int");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.HasKey("LocationID");

                    b.HasIndex("FacilityID")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("TravelReviewApp.Models.RegularUser", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecentSearches")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("RegularUsers");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportedByUserID")
                        .HasColumnType("int");

                    b.Property<int?>("ResolvedByAdminID")
                        .HasColumnType("int");

                    b.Property<int>("ReviewID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("ReportedByUserID");

                    b.HasIndex("ResolvedByAdminID");

                    b.HasIndex("ReviewID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<DateTime?>("EditDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityID")
                        .HasColumnType("int");

                    b.Property<bool>("IsReported")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpam")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("FacilityID");

                    b.HasIndex("UserID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TravelReviewApp.Models.SearchLog", b =>
                {
                    b.Property<int>("SearchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SearchID"));

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResultsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SearchID");

                    b.HasIndex("UserID");

                    b.ToTable("SearchLogs");
                });

            modelBuilder.Entity("TravelReviewApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@travelreview.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            Password = "AdminPassword123!",
                            RegistrationDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserType = 2
                        });
                });

            modelBuilder.Entity("TravelReviewApp.Models.VerifiedUser", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("FacilityID")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("FacilityID")
                        .IsUnique()
                        .HasFilter("[FacilityID] IS NOT NULL");

                    b.ToTable("VerifiedUsers");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Admin", b =>
                {
                    b.HasOne("TravelReviewApp.Models.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("TravelReviewApp.Models.Admin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelReviewApp.Models.AdminAction", b =>
                {
                    b.HasOne("TravelReviewApp.Models.Admin", "Admin")
                        .WithMany("AdminActions")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Booking", b =>
                {
                    b.HasOne("TravelReviewApp.Models.Facility", "Facility")
                        .WithMany("Bookings")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelReviewApp.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelReviewApp.Models.FacilityAmenity", b =>
                {
                    b.HasOne("TravelReviewApp.Models.Amenity", "Amenity")
                        .WithMany("FacilityAmenities")
                        .HasForeignKey("AmenityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelReviewApp.Models.Facility", "Facility")
                        .WithMany("FacilityAmenities")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Image", b =>
                {
                    b.HasOne("TravelReviewApp.Models.Facility", "Facility")
                        .WithMany("Images")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Location", b =>
                {
                    b.HasOne("TravelReviewApp.Models.Facility", "Facility")
                        .WithOne("Location")
                        .HasForeignKey("TravelReviewApp.Models.Location", "FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("TravelReviewApp.Models.RegularUser", b =>
                {
                    b.HasOne("TravelReviewApp.Models.User", "User")
                        .WithOne("RegularUser")
                        .HasForeignKey("TravelReviewApp.Models.RegularUser", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Report", b =>
                {
                    b.HasOne("TravelReviewApp.Models.User", "ReportedByUser")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelReviewApp.Models.Admin", "ResolvedByAdmin")
                        .WithMany("ResolvedReports")
                        .HasForeignKey("ResolvedByAdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelReviewApp.Models.Review", "Review")
                        .WithMany("Reports")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedByUser");

                    b.Navigation("ResolvedByAdmin");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Review", b =>
                {
                    b.HasOne("TravelReviewApp.Models.Facility", "Facility")
                        .WithMany("Reviews")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelReviewApp.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelReviewApp.Models.SearchLog", b =>
                {
                    b.HasOne("TravelReviewApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelReviewApp.Models.VerifiedUser", b =>
                {
                    b.HasOne("TravelReviewApp.Models.Facility", "Facility")
                        .WithOne("Manager")
                        .HasForeignKey("TravelReviewApp.Models.VerifiedUser", "FacilityID");

                    b.HasOne("TravelReviewApp.Models.User", "User")
                        .WithOne("VerifiedUser")
                        .HasForeignKey("TravelReviewApp.Models.VerifiedUser", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Admin", b =>
                {
                    b.Navigation("AdminActions");

                    b.Navigation("ResolvedReports");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Amenity", b =>
                {
                    b.Navigation("FacilityAmenities");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Facility", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FacilityAmenities");

                    b.Navigation("Images");

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Manager")
                        .IsRequired();

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TravelReviewApp.Models.Review", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("TravelReviewApp.Models.User", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Bookings");

                    b.Navigation("RegularUser")
                        .IsRequired();

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("VerifiedUser")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
